spring:
  application:
    name: bank-core

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: ${DB_USER:BANK_APP}
    password: ${DB_PASS:bank_secret}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # O Flyway precisa estar indentado (com 2 espaços) sob a palavra 'spring:'
  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

# A nossa API fica encostada na esquerda (fora do spring)
api:
  security:
    token:
      secret: ${JWT_SECRET:minha_chave_secreta_super_forte_para_ambiente_local_123456}