spring:
  application:
    name: bank-core

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: ${DB_USER:BANK_APP}
    password: ${DB_PASS:bank_secret}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}